apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
      - name: application-service
        image: acrladvs.azurecr.io/applicant-service:254a7c61739938186ac2324c411231dc6dac7236
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: dev
spec:
  selector:
    app: application-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer