FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["services/document-service/DocumentService/DocumentService/DocumentService.csproj", "DocumentService/"]
RUN dotnet restore "DocumentService/DocumentService.csproj"
COPY services/document-service/DocumentService/DocumentService/. DocumentService/
WORKDIR "/src/DocumentService"
RUN dotnet build "DocumentService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DocumentService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DocumentService.dll"]