apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-service
  template:
    metadata:
      labels:
        app: validation-service
    spec:
      containers:
      - name: validation-service
        image: acrladvs.azurecr.io/validation-service:3626037870b3cd5a8fed435190d3353c76c2c435
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: validation-service
  namespace: dev
spec:
  selector:
    app: validation-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP