FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["services/application-service/ApplicationService/ApplicationService/ApplicationService.csproj", "ApplicationService/"]
RUN dotnet restore "ApplicationService/ApplicationService.csproj"
COPY services/application-service/ApplicationService/ApplicationService/. ApplicationService/
WORKDIR "/src/ApplicationService"
RUN dotnet build "ApplicationService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApplicationService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApplicationService.dll"]