apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: acrladvs.azurecr.io/admin-service:3cf4ca6acf9ea37e7e342230a0dc3ccbd8da9ae5
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: dev
spec:
  selector:
    app: admin-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP