FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["services/applicant-service/ApplicantService/ApplicantService/ApplicantService.csproj", "ApplicantService/"]
RUN dotnet restore "ApplicantService/ApplicantService.csproj"
COPY services/applicant-service/ApplicantService/ApplicantService/. ApplicantService/
WORKDIR "/src/ApplicantService"
RUN dotnet build "ApplicantService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApplicantService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApplicantService.dll"]