apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: acrladvs.azurecr.io/document-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: dev
spec:
  selector:
    app: document-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer